config/routes.rb
HomeBudget::Application.routes.draw do
  devise_for :users, :controllers => { :registrations =>'registration'}

  root 'welcome#index'
  get 'dashboard' => 'welcome#dashboard'

  resources :situations do
    member do
      post :attach
      get :admin_panel
    end
    resources :items
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :situation
  belongs_to :user
  belongs_to :payment
end

app/models/participation.rb
class Participation < ActiveRecord::Base
  belongs_to :user
  belongs_to :situation
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :situation

  has_many :items
end

app/models/situation.rb
class Situation < ActiveRecord::Base
  belongs_to :owner, class_name: User

  has_many :participations
  has_many :users, through: :participations
  has_many :items
  has_many :payments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :owned_situations, class_name: Situation, foreign_key: :owner_id

  has_many :participations
  has_many :situations, through: :participations

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all

    redirect_to situation
  end

  def create
    situation = Situation.find(params[:situation_id])
    @item = Item.new(item_params)
    @item.user_id = current_user[:id]
    @item.situation = situation
    @item.save

    redirect_to situation
  end

  def show
  end

  private

  def item_params
    params.require(:item).permit(:name, :amount)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
  end

  def create
    # when payment date starts
  end

  def update_amount
    # when Due Date comes, sums up every item
  end

  def destroy
    # if deadline passed and amount equals 0
    # deadline = due_date + clearing_period

    # else if amount != 0, create new Item for the next payment, and then destroy
  end
end

app/controllers/registration_controller.rb
class RegistrationController < Devise::RegistrationsController
  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.username = params[:user][:username]
    @user.bank = params[:user][:bank]
    @user.account_number = params[:user][:account_number]
    @user.adress = params[:user][:adress]
    @user.password = params[:user][:password]
    @user.email = params[:user][:email]

    if @user.errors.blank?
      @user.save
      redirect_to dashboard_path
    else
      render :action => "new"
    end
  end
end

app/controllers/situations_controller.rb
class SituationsController < ApplicationController
  def index
    @situations = Situation.all

    redirect_to dashboard_path
  end

  def new
  end

  def create
    @situation = Situation.new(situation_params)
    @situation.owner = current_user
    @situation.save

    redirect_to dashboard_path
  end

  def show
    @situation = Situation.find(params[:id])
    @owner = @situation.owner
  end

  def attach
    @user = User.find_by(email: params[:email])
    @situation = Situation.find(params[:id])

    if @user
      Participation.find_or_create_by(user_id: @user.id, situation_id: @situation.id)
    end

    redirect_to @situation
  end

  private

  def situation_params
    params.require(:situation).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def dashboard
    @situations = Situation.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HomeBudget</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/situations/admin_panel.html.haml
%h1 Hello!

app/views/situations/new.html.haml
= simple_form_for [Situation.new] do |f|
  = f.input :name, label: "New Thread's name"
  = f.submit

app/views/situations/show.html.haml
%h3 Thread owned by #{@owner.username}
%h4= link_to 'Go to the administration panel.', admin_panel_situation_path(@situation)

= simple_form_for [@situation, Item.new] do |f|
  = f.input :name, label: "New Item's name"
  = f.input :amount, label: "Item's value"
  = f.submit

- @situation.items.each do |item|
  %p= item.name
  %p= item.amount

= form_tag attach_situation_path(@situation) do
  = text_field_tag :email
  = submit_tag "Attach User"

%h3 Users participating in this thread:
%ul
- @situation.users.each do |user|
  %li= "#{user.username}, #{user.email}"

app/views/welcome/dashboard.html.haml
%h1 Welcome to Home Budget!
%h3 Here is your Thread's list. Choose one to go to the Thread's dashboard or go ahead and create a new one.

= simple_form_for [Situation.new] do |f|
  = f.input :name, label: "New Thread's name"
  = f.submit

%ul
- @situations.each do |situation|
  - if situation.users.include?(current_user) or situation.owner == current_user
    %li= link_to situation.name, situation

app/views/welcome/index.html.haml
%h1 Home Budget

- if user_signed_in?

  %h3 Hi #{current_user.username}! You have succesfully sighed in!
  = link_to "Sign Out", destroy_user_session_path, :method => :delete
  = link_to "Dashboard", dashboard_path

- else

  %h2 Witaj na stronie Budżetu Domowego!
  = link_to "Sign In", new_user_session_path, :method => :get
  = link_to "Sign up", new_user_registration_path, :method => :get